# Uncomment this line to define a global platform for your project
 source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, ‘9.0’
# Uncomment this line if you're using Swift
 use_frameworks!

pod 'Mapbox-iOS-SDK','~> 3.1'

target 'Milieu' do

  pod 'STPopup', '~> 1.6'
  pod 'Alamofire', '~> 4.0'
  pod 'PNChart'
  pod 'Fabric'
  #pod 'NVActivityIndicatorView'

end

target 'MilieuTests' do

end

target 'MilieuUITests' do

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

