# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!


target 'Milieu' do

  pod 'STPopup', '~> 1.5.0'

end

target 'MilieuTests' do

end

target 'MilieuUITests' do

end

